[package]
name = "wave"
version = "0.1.0"
edition = "2021"

[dependencies]
wave-core = { path = "../wave-core" }
wave-proxy = { path = "../wave-proxy" }

iroh = { version = "0.31" }
anyhow = { workspace = true }
derive_more = { workspace = true, features = ["from", "display", "error"] }
tokio = { workspace = true, features = ["net"] }
