[package]
name = "wave-core"
version = "0.1.0"
edition = "2021"

[dependencies]
iroh = { workspace = true }
derive_more = { version = "*", features = [
    "from",
    "display",
    "as_ref",
    "as_mut",
] }

serde_bytes = { workspace = true }
serde = { workspace = true, features = ["derive"] }
rmp-serde = "1.3"

anyhow = { workspace = true }

tokio = { workspace = true, features = [] }
futures = { version = "0.3" }
async-trait = { workspace = true }
async-stream = { version = "0.3" }

ulid = { version = "1.1", features = ["serde"] }

bytes = { version = "1.7" }
